### ISSUE TITLE
Cannot allocate class N data area

### ISSUE THREAD

**Issue by qathy** [ssrg-vt/SlimGuard#8]
On a CentOS Linux release 7.8.2003 (Core), I'm experiencing the following error with any binary when trying to use SlimGuard:
ls: mmap(8589934592): Cannot allocate memory
ls: Cannot allocate class 3 data area

As a matter of fact, this is experienced using the simplest mode:
LD_PRELOAD=/path/to/libSlimGuard.so /your/app

The class number depends on the binary used:
cat: mmap(8589934592): Cannot allocate memory
cat: Cannot allocate class 1 data area

a.out: mmap(8589934592): Cannot allocate memory
a.out: Cannot allocate class 162 data area

**Comment by olivierpierre** [comment]
Hello, thanks for reporting this issue. It may be due to a system limit of the amount of virtual memory that can be reserved by mmap. Could you try replacing on this [line](https://github.com/ssrg-vt/SlimGuard/blob/master/include/slimguard.h#L32) `8UL` by `4UL` or `2UL`?

**Comment by qathy** [comment]
Thank you for this prompt answer.
Using 4UL instead of 8UL doesn't resolve the issue, but 2UL does.
I'll use it like that for now.
Best regards.

Le sam. 3 oct. 2020 à 10:35, Pierre Olivier <notifications@github.com> a
écrit :

**Comment by olivierpierre** [comment]
Great!
